### ISSUE TITLE
Add support for Unicode characters in URLs

### ISSUE THREAD

**Issue by KL-7** [twitter/twitter-text-conformance#66]
Twitter-text fails to pass this test from #52: 

``` yaml
description: "Autolink URLs with unicode chars in them"
text: "See: http://example.com/tsa-pre✓™ is a link"
expected: "See: <a href=\"http://example.com/tsa-pre✓™\">http://example.com/tsa-pre✓™</a> is a link"
```

I removed it from the conformance suit in #65, because it breaks all Travis CI builds for twitter-text libraries, but we still need to address this case at some point.
